actions = { label = "Actions", bind = "control+3" }
test = { label = "Test", bind = "t" }
test1 = { label = "Test", bind = "y" }
test2 = { label = "Test", bind = "u" }

close = { label = "Close", bind = "escape" }
navigate-next = { label = "Next", bind = "arrowdown" }
navigate-prev = { label = "Previous", bind = "arrowup" }
navigate-next-page = { label = "Next Page", bind = "pagedown" }
navigate-prev-page = { label = "Previous Page", bind = "pageup" }
select = { label = "Select", bind = "enter" }
copy = { label = "Copy", icon = "copy", bind = "control+c" }
paste = { label = "Paste", icon = "paste", bind = "control+v" }
delete = { label = "Delete", icon = "trash-can", bind = "delete" }
add-storage = { label = "Add storage...", icon = "database", bind = "control+s" }
add-dir = { label = "Add directory...", icon = "folder-open", bind = "control+d" }
add-zip = { label = "Add Zip File...", icon = "file-zipper", bind = "control+z" }
add-rff = { label = "Add Rff File...", icon = "box", bind = "control+r" }
add-grp = { label = "Add Grp File...", icon = "box", bind = "control+g" }
add-memory = { label = "Add Memory Storage...", icon = "memory", bind = "control+m" }
left = { bind = "arrowleft" }
right = { bind = "arrowright" }
up = { bind = "arrowup" }
down = { bind = "arrowdown" }
pageup = { bind = "pageup" }
pagedown = { bind = "pagedown" }

[menu]
close = { parent = "close" }

[win]
close = { parent = "close" }

[message-box]
close = { parent = "close" }
ok = { bind = "enter" }
cancel = { bind = "escape" }

[progress-box]
stop = { parent = "close" }
resume-pause = { bind = "p" }

[overwrite-box]
yes = { parent = "select" }
no = { parent = "close" }
all-yes = { bind = "control+enter" }
all-no = { bind = "control+escape" }

[list]
next = { parent = "navigate-next" }
prev = { parent = "navigate-prev" }
next-page = { parent = "navigate-next-page" }
prev-page = { parent = "navigate-prev-page" }
select = { parent = "select" }

[table]
next = { parent = "navigate-next" }
prev = { parent = "navigate-prev" }
next-page = { parent = "navigate-next-page" }
prev-page = { parent = "navigate-prev-page" }
select = { parent = "select" }
select-all = { bind = "control+a" }

[painter]
label = "Painter"
bind = "control+p"
toggle-mode = { bind = "m" }
add-shape = { bind = " " }
grid = { bind = "g" }
grid-inc = { bind = "]" }
grid-dec = { bind = "[" }
reset-workplane = { bind = "backspace" }

[fs]
label = "File System"
bind = "control+f"
add-storage = { parent = "add-storage" }
add-dir = { parent = "add-dir" }
add-zip = { parent = "add-zip" }
add-rff = { parent = "add-rff" }
add-grp = { parent = "add-grp" }
add-res = { label = "Add resource", bind = "control+r" }
add-menu = { bind = "m" }
refresh = { label = "Refresh", icon = "arrows-rotate", bind = "f5" }
search = { bind = "/" }
clear-search = { bind = "backspace" }
copy = { parent = "copy" }
paste = { parent = "paste" }
delete = { parent = "delete" }
create-engine-blood = { label = "Blood", icon = "gears", bind = "b" }
create-engine-duke = { label = "Duke", icon = "gears", bind = "d" }
create-engine-fury = { label = "Ion Fury", icon = "gears", bind = "f" }
create-engine = { bind = 'c' }

[controls]
check = { label = "Check", bind = " " }

[controls.numberbox]
micro-step-up = { label = "Micro step up", bind = "alt+arrowup" }
micro-step-down = { label = "Micro step down", bind = "alt+arrowdown" }
macro-step-up = { label = "Macro step up", bind = "pageup" }
macro-step-down = { label = "Macro step down", bind = "pagedown" }
step-up = { label = "Step up", bind = "arrowup" }
step-down = { label = "Step down", bind = "arrowdown" }
escape = { label = "Escape", bind = "escape" }
enter = { label = "Eneter", bind = "enter" }
undo = { label = "Undo", bind = "control+z" }

[controls.textbox]
enter = { label = "Enter", bind = "enter" }
close = { parent = "close" }
suggestions = { bind = "pagedown" }

[input-text-box]
ok = { parent = "select" }
cancel = { parent = "close" }

[art-editor]
label = "ART Editor"
left = { parent = "left" }
right = { parent = "right" }
up = { parent = "up" }
down = { parent = "down" }
pageup = { parent = "pageup" }
pagedown = { parent = "pagedown" }
search = { label = "Search", bind = "/" }
clear-search = { bind = "escape" }
next-plu = { label = "Next PalSwap", bind = "p" }
prev-plu = { label = "Previous PalSwap", bind = "o" }
reset-plu = { label = "Reset PalSwap", bind = "control+p" }
plu = { bind = "shift+p" }
center = { label = "Center Picture", bind = "backspace" }
toggle-grid = { bind = "g" }
grid = { bind = "control+g" }
grid-inc = { bind = "]" }
grid-dec = { bind = "[" }
toggle-repeat = { label = "Toggle Repeat", bind = "r" }
toggle-scale = { label = "Toggle SuperSample", bind = "s" }
copy = { parent = "copy" }
blend = { bind = "b" }
toggle-upscale-preview = { bind = "i" }

[art-select]
label = "ART Select"
left = { parent = "left" }
right = { parent = "right" }
up = { parent = "up" }
down = { parent = "down" }
pageup = { parent = "pageup" }
pagedown = { parent = "pagedown" }
select = { parent = "select" }

[board-view]
label = "Board View"
forward = { bind = 'w' }
back = { bind = 's' }
strife-left = { bind = 'a' }
strife-right = { bind = 'd' }
print = { bind = ' ' }
'vis_inc' = { bind = 'o' }
'vis_dec' = { bind = 'p' }
'shadow_off_dec' = { bind = 'j' }
'shadow_off_inc' = { bind = 'k' }
reset = { bind = '/' }
undo = { bind = 'control+z' }
lookaim = { bind = 'mouse2' }
pan-up = { bind = "arrowup" }
pan-down = { bind = "arrowdown" }
pan-left = { bind = "arrowleft" }
pan-right = { bind = "arrowright" }
pan-up-one = { bind = "alt+arrowup" }
pan-down-one = { bind = "alt+arrowdown" }
pan-left-one = { bind = "alt+arrowleft" }
pan-right-one = { bind = "alt+arrowright" }
repeat-up = { bind = "control+arrowup" }
repeat-down = { bind = "control+arrowdown" }
repeat-left = { bind = "control+arrowleft" }
repeat-right = { bind = "control+arrowright" }
pan-repeat-reset = { bind = "/" }
sprite-mode = { bind = "r" }
flip = { bind = "f" }
delete = { bind = "delete" }
up = { bind = "pageup" }
down = { bind = "pagedown" }
rot-up = { bind = "." }
rot-down = { bind = "," }
move = { bind = "mouse0" }
move-vertical = { bind = "alt" }
move-parallel = { bind = "shift" }
grid-inc = { bind = "]" }
grid-dec = { bind = "[" }
draw = { bind = " " }
draw-rect = { bind = "shift+ " }
draw-back = { bind = "backspace" }
shade = { bind = "b" }
split-wall = { bind = "insert" }
split-sector = { bind = "control+insert" }
fill-loop = { bind = "alt+s" }
delete-loop = { bind = "alt+delete" }
delete-full = { bind = "control+delete" }
set-first-wall = { bind = "alt+f" }
set-picnum = { bind = "v" }
shadow-up = { bind = "wheeldown" }
shadow-down = { bind = "wheelup" }
shadow-up-fast = { bind = "shift+wheeldown" }
shadow-down-fast = { bind = "shift+wheelup" }
save = { bind = "control+s" }

[rectifier]
label = "Rectifier"
bind = "r"
toggle = { bind = 'tab' }
paste = { parent = 'paste' }

[engines-context]
label = "Engines"
bind = "e"
open-map = { label = 'Open Map...' }
open-voxel = { label = 'Open Voxel File...' }
art-editor = { label = 'Open Art Editor...' }

[engines-context-create]
label = "Create Engine Context"
add-storage = { parent = "add-storage" }
add-dir = { parent = "add-dir" }
add-zip = { parent = "add-zip" }
add-rff = { parent = "add-rff" }
add-grp = { parent = "add-grp" }
add-memory = { parent = "add-memory" }
delete = { icon = "trash", bind = "delete" }
move-up = { icon = "caret-up", bind = "control+arrowup" }
move-down = { icon = "caret-down", bind = "control+arrowdown" }

[select-storage-fs]
label = "Select Storage"
add-storage = { bind = "control+a" }
close = { parent = "close" }
select = { parent = "select" }

[settings]
label = "Settings"
bind = "g"

[text-editor]
label = "Text Editor"
bind = "x"
